// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiPWOU7gBLAad8ZlBuCWgqEJ-NKSZ6p-c',
    appId: '1:350240527591:web:84ece770d7602cfd84fe42',
    messagingSenderId: '350240527591',
    projectId: 'copia-b6e7c',
    authDomain: 'copia-b6e7c.firebaseapp.com',
    storageBucket: 'copia-b6e7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6UZVer0hZKJbXp-nwIjaNBc-MhJ-7VJo',
    appId: '1:350240527591:android:2eba90ccba9931f084fe42',
    messagingSenderId: '350240527591',
    projectId: 'copia-b6e7c',
    storageBucket: 'copia-b6e7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo42T56k0e5-PPOzFFKj2JDTYVPEcnvTw',
    appId: '1:350240527591:ios:2c90fdafa9453f8984fe42',
    messagingSenderId: '350240527591',
    projectId: 'copia-b6e7c',
    storageBucket: 'copia-b6e7c.appspot.com',
    iosClientId: '350240527591-3ftcfegpqd3pk7c343jh6ac25gscoql2.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo42T56k0e5-PPOzFFKj2JDTYVPEcnvTw',
    appId: '1:350240527591:ios:2c90fdafa9453f8984fe42',
    messagingSenderId: '350240527591',
    projectId: 'copia-b6e7c',
    storageBucket: 'copia-b6e7c.appspot.com',
    iosClientId: '350240527591-3ftcfegpqd3pk7c343jh6ac25gscoql2.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled2',
  );
}
